# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

cache_dir: /Users/kevinyang/Desktop/LeWM/le-wm/.stable-wm # use stable-worldmodel default cache
